server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api}

spring:
  application:
    name: fate-compass-backend
  
  # Oracle Database Configuration - 生產環境
  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: ${DATABASE_USERNAME:fate_compass}
    password: ${DATABASE_PASSWORD:oracle123}
    driver-class-name: oracle.jdbc.OracleDriver
    
  # JPA Configuration - 生產環境優化
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}  # 生產環境使用validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${JPA_SHOW_SQL:false}  # 生產環境關閉SQL日誌
    properties:
      hibernate:
        format_sql: false
        
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:fate-compass-secret-key-for-jwt-token-generation-2024}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours

# cnchar微服務配置
cnchar:
  service:
    url: ${CNCHAR_SERVICE_URL:http://localhost:3001}
    timeout: ${CNCHAR_TIMEOUT:5000}

# CORS Configuration - 生產環境
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8081}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging Configuration - 生產環境
logging:
  level:
    com.fatecompass: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: ${ROOT_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/fate-compass.log}

# Management Endpoints - 生產環境限制
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info}
      base-path: ${MANAGEMENT_BASE_PATH:/actuator}
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when-authorized}
  security:
    enabled: true 