server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: fate-compass-backend
  
  # Oracle Database Configuration
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: fate_compass
    password: oracle123
    driver-class-name: oracle.jdbc.OracleDriver
    
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # Security Configuration
  security:
    jwt:
      secret: fate-compass-secret-key-for-jwt-token-generation-2024
      expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:8081
    - http://127.0.0.1:3000
    - http://127.0.0.1:8081
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.fatecompass: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fate-compass.log

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 